import json
import numpy as np
import skfuzzy as fuzz
from skfuzzy import control as ctrl
import sys

class Fuzzy():

    def __init__(self):
        # data_original = GlucoseData.query.filter_by(owner_id=current_user.id).all()
        # Variáveis do problema
        self.fasting = ctrl.Antecedent(np.arange(0,1.1,0.1),'fasting')
        self.exercise = ctrl.Antecedent(np.arange(0,1.1,0.1),'exercise')
        self.stress = ctrl.Antecedent(np.arange(0,1.1,0.1),'stress')
        self.medication = ctrl.Antecedent(np.arange(0,1.1,0.1),'medication')
        self.glicemia = ctrl.Antecedent(np.arange(70,155,1),'glicemia')
        self.trend = ctrl.Consequent(np.arange(0,101,1),'trend')

        # Cria um mapeamento entre os valores nítidos e difusos
        # Como função pertinencia padrão "Triângulo"
        self.fasting.automf(names=['never','sometimes','always'])
        self.exercise.automf(names=['never','sometimes','always'])
        self.stress.automf(names=['never','sometimes','always'])
        self.medication.automf(names=['never','sometimes','always'])
        
        # Cria a função pertinencia da glicemia
        self.glicemia['normal'] = fuzz.trimf(self.glicemia.universe, [0,70,125])
        self.glicemia['pre-diabetes'] = fuzz.gaussmf(self.glicemia.universe, 125,5)
        self.glicemia['diabetes'] = fuzz.trapmf(self.glicemia.universe, [129,135,160,160])

        # Cria a função pertinencia da tendência
        self.trend['descent'] = fuzz.trimf(self.trend.universe, [0,0,50])
        self.trend['stable'] = fuzz.trimf(self.trend.universe, [35,50,65])
        self.trend['climb'] = fuzz.trimf(self.trend.universe, [50,100,100])

        self.rules = self._get_rules_fuzzy(
            self.fasting,
            self.exercise,
            self.stress,
            self.medication,
            self.glicemia,
            self.trend
        )
        self.trend_ctrl = ctrl.ControlSystem(self.rules)
        

    def compute(self, item):
        trend_ctrl = self.trend_ctrl
        trend_simulador = ctrl.ControlSystemSimulation(trend_ctrl)

        trend_simulador.input['fasting'] = np.mean(item["fasting"])
        trend_simulador.input['exercise'] = np.mean(item["exercise"])
        trend_simulador.input['stress'] = np.mean(item["stress"])
        trend_simulador.input['medication'] = np.mean(item["medication"])
        trend_simulador.input['glicemia'] = np.mean(item["value"])  
        trend_simulador.compute()
        result = trend_simulador.output['trend']
        descent_label = fuzz.interp_membership(self.trend.universe, self.trend['descent'].mf, result)
        stable_label = fuzz.interp_membership(self.trend.universe, self.trend['stable'].mf, result)
        climb_label = fuzz.interp_membership(self.trend.universe, self.trend['climb'].mf, result)
        label = [(descent_label, 'decrease'), (stable_label, 'stabilize'), (climb_label, 'increase')]
        label.sort(reverse=True)
        print(label)
        return result, label[0][1]


    def _get_rules_fuzzy(self, fasting, exercise, stress, medication, glicemia, trend):
        rule = []
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['sometimes'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['sometimes'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['sometimes'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['sometimes'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['sometimes'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['sometimes'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['sometimes'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['sometimes'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['sometimes'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['never'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['never'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['never'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['never'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['never'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['never'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['never'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['never'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['never'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['always'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['always'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['always'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['always'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['always'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['always'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['always'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['always'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['always'] & medication['sometimes'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['sometimes'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['sometimes'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['sometimes'] & medication['sometimes'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['sometimes'] & medication['sometimes'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['sometimes'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['sometimes'] & medication['sometimes'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['sometimes'] & medication['sometimes'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['sometimes'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['sometimes'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['never'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['never'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['never'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['never'] & medication['sometimes'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['never'] & medication['sometimes'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['never'] & medication['sometimes'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['never'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['never'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['never'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['always'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['always'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['always'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['always'] & medication['sometimes'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['always'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['always'] & medication['sometimes'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['always'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['always'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['always'] & medication['sometimes'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['sometimes'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['sometimes'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['sometimes'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['sometimes'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['sometimes'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['sometimes'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['sometimes'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['sometimes'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['sometimes'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['never'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['never'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['never'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['never'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['never'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['never'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['never'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['never'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['never'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['always'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['always'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['always'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['always'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['always'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['always'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['always'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['always'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['always'] & medication['sometimes'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['sometimes'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['sometimes'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['sometimes'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['sometimes'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['sometimes'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['sometimes'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['sometimes'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['sometimes'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['sometimes'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['never'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['never'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['never'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['never'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['never'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['never'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['never'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['never'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['never'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['always'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['always'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['always'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['always'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['always'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['always'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['always'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['always'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['always'] & medication['never'] & glicemia['diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['sometimes'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['sometimes'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['sometimes'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['sometimes'] & medication['never'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['sometimes'] & medication['never'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['sometimes'] & medication['never'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['sometimes'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['sometimes'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['sometimes'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['never'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['never'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['never'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['never'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['never'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['never'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['never'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['never'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['never'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['always'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['always'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['always'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['always'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['always'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['always'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['always'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['always'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['always'] & medication['never'] & glicemia['normal'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['sometimes'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['sometimes'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['sometimes'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['sometimes'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['sometimes'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['sometimes'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['sometimes'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['sometimes'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['sometimes'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['never'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['never'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['never'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['never'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['never'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['never'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['never'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['never'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['never'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['always'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['always'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['always'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['always'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['always'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['always'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['always'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['always'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['always'] & medication['never'] & glicemia['pre-diabetes'], trend['climb']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['sometimes'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['sometimes'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['sometimes'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['sometimes'] & medication['always'] & glicemia['diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['sometimes'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['sometimes'] & medication['always'] & glicemia['diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['sometimes'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['sometimes'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['sometimes'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['never'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['never'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['never'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['never'] & medication['always'] & glicemia['diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['never'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['never'] & medication['always'] & glicemia['diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['never'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['never'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['never'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['always'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['always'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['always'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['always'] & medication['always'] & glicemia['diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['always'] & medication['always'] & glicemia['diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['always'] & medication['always'] & glicemia['diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['always'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['always'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['always'] & medication['always'] & glicemia['diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['sometimes'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['sometimes'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['sometimes'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['sometimes'] & medication['always'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['sometimes'] & medication['always'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['sometimes'] & medication['always'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['sometimes'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['sometimes'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['sometimes'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['never'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['never'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['never'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['never'] & medication['always'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['never'] & medication['always'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['never'] & medication['always'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['never'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['never'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['never'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['always'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['always'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['always'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['always'] & medication['always'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['always'] & medication['always'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['always'] & medication['always'] & glicemia['normal'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['always'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['always'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['always'] & medication['always'] & glicemia['normal'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['sometimes'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['sometimes'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['sometimes'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['sometimes'] & medication['always'] & glicemia['pre-diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['sometimes'] & medication['always'] & glicemia['pre-diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['sometimes'] & medication['always'] & glicemia['pre-diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['sometimes'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['sometimes'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['sometimes'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['never'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['never'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['never'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['never'] & medication['always'] & glicemia['pre-diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['never'] & medication['always'] & glicemia['pre-diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['never'] & medication['always'] & glicemia['pre-diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['never'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['never'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['never'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['sometimes'] & stress['always'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['never'] & stress['always'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['sometimes'] & exercise['always'] & stress['always'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['sometimes'] & stress['always'] & medication['always'] & glicemia['pre-diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['never'] & stress['always'] & medication['always'] & glicemia['pre-diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['never'] & exercise['always'] & stress['always'] & medication['always'] & glicemia['pre-diabetes'], trend['descent']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['sometimes'] & stress['always'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['never'] & stress['always'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        rule.append(ctrl.Rule(fasting['always'] & exercise['always'] & stress['always'] & medication['always'] & glicemia['pre-diabetes'], trend['stable']))
        return rule
    
f = Fuzzy()
data = json.loads(sys.argv[1])
a = f.compute(item=data)
print(a)